<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="fn" uri="jakarta.tags.functions" %>
<!DOCTYPE html><html lang="vi"><head><title>Chi tiết người dùng</title></head><body>
<a class="back-link" href="<c:url value='/admin/users'/>"><span aria-hidden="true">←</span> Trở về danh sách người dùng</a>
<div class="page-heading"><div><h1>Chi tiết người dùng</h1></div><a class="btn btn-primary" href="<c:url value='/admin/users/${managedUser.id}/edit'/>">Chỉnh sửa người dùng</a></div>
<%@ include file="../../fragments/flash.jsp" %>
<div class="form-layout"><section class="panel"><div class="detail-body"><div class="detail-hero"><span class="detail-icon row-avatar" aria-hidden="true"><c:out value="${fn:toUpperCase(fn:substring(managedUser.fullName, 0, 1))}"/></span><div><h2><c:out value="${managedUser.fullName}"/></h2><span class="status-badge ${managedUser.active ? '' : 'status-inactive'}">${managedUser.active ? 'Hoạt động' : 'Đã khóa'}</span></div></div><dl class="detail-rows"><div class="detail-row"><dt>Mã người dùng</dt><dd><span class="muted-id">#${managedUser.id}</span></dd></div><div class="detail-row"><dt>Tên đăng nhập</dt><dd><c:out value="${managedUser.username}"/></dd></div><div class="detail-row"><dt>Họ và tên</dt><dd><c:out value="${managedUser.fullName}"/></dd></div><div class="detail-row"><dt>Email</dt><dd><c:out value="${managedUser.email}"/></dd></div><div class="detail-row"><dt>Vai trò</dt><dd><span class="role-badge ${managedUser.role == 'ADMIN' ? 'role-admin' : ''}">${managedUser.role == 'ADMIN' ? 'Quản trị viên (ADMIN)' : 'Người dùng (USER)'}</span></dd></div><div class="detail-row"><dt>Trạng thái</dt><dd>${managedUser.active ? 'Hoạt động' : 'Đã khóa'}</dd></div></dl></div><div class="form-actions"><a href="<c:url value='/admin/users'/>" class="btn btn-outline-secondary">Trở về danh sách</a><form method="post" action="<c:url value='/admin/users/${managedUser.id}/delete'/>" data-confirm-delete><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"><button type="submit" class="btn btn-outline-danger">Xóa người dùng</button></form></div></section></div>
</body></html>
