<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<!DOCTYPE html><html lang="vi"><head><title>${editMode ? 'Chỉnh sửa người dùng' : 'Thêm người dùng'}</title></head><body>
<a class="back-link" href="<c:url value='/admin/users'/>"><span aria-hidden="true">←</span> Trở về danh sách người dùng</a>
<div class="page-heading"><div><h1>${editMode ? 'Chỉnh sửa người dùng' : 'Thêm người dùng'}</h1></div></div>
<%@ include file="../../fragments/flash.jsp" %>
<c:choose><c:when test="${editMode}"><c:url var="formAction" value="/admin/users/${userId}"/></c:when><c:otherwise><c:url var="formAction" value="/admin/users"/></c:otherwise></c:choose>
<div class="form-layout"><section class="panel form-panel"><div class="panel-header"><div><h2>Thông tin tài khoản</h2></div></div>
<form:form modelAttribute="userForm" method="post" action="${formAction}" htmlEscape="true" autocomplete="off">
    <div class="form-body"><form:errors path="*" element="div" cssClass="alert alert-danger" htmlEscape="true"/>
        <div class="row g-4 mb-4"><div class="col-md-6"><label for="username" class="form-label">Tên đăng nhập <span class="required">*</span></label><form:input path="username" id="username" cssClass="form-control" cssErrorClass="form-control is-invalid" maxlength="50" required="required" placeholder="Ví dụ: nguyenvana" autocomplete="off" aria-describedby="username-help username-error"/><form:errors path="username" id="username-error" cssClass="field-error" htmlEscape="true"/><div id="username-help" class="form-text">Tối đa 50 ký tự, gồm chữ, số, dấu chấm, gạch dưới hoặc gạch ngang.</div></div><div class="col-md-6"><label for="fullName" class="form-label">Họ và tên <span class="required">*</span></label><form:input path="fullName" id="fullName" cssClass="form-control" cssErrorClass="form-control is-invalid" maxlength="120" required="required" placeholder="Ví dụ: Nguyễn Văn An" autocomplete="name" aria-describedby="fullName-error"/><form:errors path="fullName" id="fullName-error" cssClass="field-error" htmlEscape="true"/></div></div>
        <div class="mb-4"><label for="email" class="form-label">Địa chỉ email <span class="required">*</span></label><form:input path="email" id="email" type="email" cssClass="form-control" cssErrorClass="form-control is-invalid" maxlength="254" required="required" placeholder="ten@vidu.com" autocomplete="email" aria-describedby="email-error"/><form:errors path="email" id="email-error" cssClass="field-error" htmlEscape="true"/></div>
        <div class="mb-4"><label for="password" class="form-label">${editMode ? 'Mật khẩu mới' : 'Mật khẩu'} <c:if test="${not editMode}"><span class="required">*</span></c:if></label><div class="password-wrap"><c:choose><c:when test="${editMode}"><form:password path="password" id="password" cssClass="form-control" cssErrorClass="form-control is-invalid" showPassword="false" minlength="8" maxlength="72" autocomplete="new-password" placeholder="Để trống nếu không đổi mật khẩu" aria-describedby="password-help password-error"/></c:when><c:otherwise><form:password path="password" id="password" cssClass="form-control" cssErrorClass="form-control is-invalid" showPassword="false" minlength="8" maxlength="72" required="required" autocomplete="new-password" placeholder="Nhập mật khẩu cho tài khoản" aria-describedby="password-help password-error"/></c:otherwise></c:choose><button type="button" class="password-toggle" data-toggle-password="password" aria-label="Hiện mật khẩu" aria-pressed="false">Hiện</button></div><form:errors path="password" id="password-error" cssClass="field-error" htmlEscape="true"/><div id="password-help" class="form-text">Từ 8–72 ký tự.${editMode ? ' Để trống nếu không đổi mật khẩu.' : ''}</div></div>
        <div class="mb-4"><label for="role" class="form-label">Vai trò <span class="required">*</span></label><form:select path="role" id="role" cssClass="form-select" cssErrorClass="form-select is-invalid" aria-describedby="role-error"><c:forEach var="roleOption" items="${roles}"><form:option value="${roleOption}" label="${roleOption == 'ADMIN' ? 'Quản trị viên (ADMIN)' : 'Người dùng (USER)'}"/></c:forEach></form:select><form:errors path="role" id="role-error" cssClass="field-error" htmlEscape="true"/></div>
        <div><label class="form-label" for="active">Trạng thái</label><div class="form-check form-switch"><form:checkbox path="active" id="active" cssClass="form-check-input" role="switch"/><label class="form-check-label" for="active">Hoạt động</label></div><form:errors path="active" cssClass="field-error" htmlEscape="true"/></div>
    </div>
    <div class="form-actions"><div class="d-flex gap-2 ms-auto"><a class="btn btn-outline-secondary" href="<c:url value='/admin/users'/>">Hủy</a><button type="submit" class="btn btn-primary">${editMode ? 'Lưu thay đổi' : 'Tạo người dùng'}</button></div></div>
</form:form></section></div>
</body></html>
